// Minimal LuneI18n with DE/FR/EN
const LuneI18n=(function(){
  const dict={
    en:{ app_title:'Lune Skin Analysis', tagline:'Your private, premium skin analysis', subtag:'Photograph once, receive a personalized plan.', start_cta:'Start Analysis', camera_title:'Camera', camera_hint:'Use good lighting; keep the camera steady.', capture:'Capture Photo', upload:'Upload Photo', quick_title:'Your Skin Score', quick_lead:'An instant orientation to guide your plan.', intake_title:'Your Profile', name:'Name', email:'Email', skin_type:'Skin Type', goals:'Skin Goals', allergies:'Allergies', budget:'Budget', routine_pref:'Routine Preference', back:'Back', continue:'Continue', payment_title:'Payment', payment_hint:'This is a simulation (no real payment).', view_report:'View Report', band_great:'Great', band_fair:'Fair', band_support:'Needs Support', reportTitle:'Your Lune Skin Report', reportSubtitle:'A premium, private skin analysis—crafted just for you.', executiveSummary:'Executive Summary', keyFindings:'Key Findings (ordered by priority)', morningRoutine:'Morning Routine', eveningRoutine:'Evening Routine', weeklyRoutine:'Weekly Rhythm', actives:'Active Ingredients', avoidList:'Avoid List', personalNotes:'Personal Notes', analysisPhoto:'Analysis Photo', disclaimer:'This report is informational and not medical advice.', retinoidNights:'Retinoid nights', nonRetinoidNights:'Non‑retinoid nights' },
    de:{ app_title:'Lune Hautanalyse', tagline:'Ihre private, hochwertige Hautanalyse', subtag:'Ein Foto – ein persönlicher Plan.', start_cta:'Analyse starten', camera_title:'Kamera', camera_hint:'Gutes Licht verwenden; Kamera ruhig halten.', capture:'Foto aufnehmen', upload:'Foto hochladen', quick_title:'Ihr Haut‑Score', quick_lead:'Eine schnelle Orientierung für Ihren Plan.', intake_title:'Ihr Profil', name:'Name', email:'E‑Mail', skin_type:'Hauttyp', goals:'Hautziele', allergies:'Allergien', budget:'Budget', routine_pref:'Routine‑Vorliebe', back:'Zurück', continue:'Weiter', payment_title:'Zahlung', payment_hint:'Dies ist eine Simulation (keine echte Zahlung).', view_report:'Bericht ansehen', band_great:'Sehr gut', band_fair:'Gut', band_support:'Unterstützung nötig', reportTitle:'Ihr Lune Hautbericht', reportSubtitle:'Eine private Premium‑Hautanalyse – nur für Sie.', executiveSummary:'Zusammenfassung', keyFindings:'Wichtigste Erkenntnisse (priorisiert)', morningRoutine:'Morgenroutine', eveningRoutine:'Abendroutine', weeklyRoutine:'Wöchentlicher Rhythmus', actives:'Wirkstoffe', avoidList:'Zu vermeiden', personalNotes:'Persönliche Notizen', analysisPhoto:'Analyse‑Foto', disclaimer:'Dieser Bericht ist informativ und keine medizinische Beratung.', retinoidNights:'Retinoid‑Nächte', nonRetinoidNights:'Nicht‑Retinoid‑Nächte' },
    fr:{ app_title:'Analyse de peau Lune', tagline:'Votre analyse de peau privée et premium', subtag:'Prenez une photo, recevez un plan personnalisé.', start_cta:'Commencer l’analyse', camera_title:'Caméra', camera_hint:'Utilisez une bonne lumière ; gardez la caméra stable.', capture:'Prendre la photo', upload:'Téléverser la photo', quick_title:'Votre score peau', quick_lead:'Une orientation instantanée pour guider votre plan.', intake_title:'Votre profil', name:'Nom', email:'E‑mail', skin_type:'Type de peau', goals:'Objectifs de peau', allergies:'Allergies', budget:'Budget', routine_pref:'Préférence de routine', back:'Retour', continue:'Continuer', payment_title:'Paiement', payment_hint:'Ceci est une simulation (pas de paiement réel).', view_report:'Voir le rapport', band_great:'Excellent', band_fair:'Bien', band_support:'Besoin de soutien', reportTitle:'Votre rapport de peau Lune', reportSubtitle:'Une analyse de peau privée et premium – conçue pour vous.', executiveSummary:'Résumé', keyFindings:'Constats clés (par priorité)', morningRoutine:'Routine du matin', eveningRoutine:'Routine du soir', weeklyRoutine:'Rythme hebdomadaire', actives:'Ingrédients actifs', avoidList:'À éviter', personalNotes:'Notes personnelles', analysisPhoto:'Photo d’analyse', disclaimer:'Ce rapport est informatif et ne constitue pas un avis médical.', retinoidNights:'Soirs avec rétinoïde', nonRetinoidNights:'Soirs sans rétinoïde' }
  };
  let current='en';
  return{ t:(k)=> (dict[current]&&dict[current][k])|| (dict['en'][k]||k), setLocale:(l)=>{ current= (['en','de','fr'].includes(l)? l:'en'); }, locale:()=>current };
})();
